import Head from 'next/head'
import { fetchSleepData } from 'lib/oura'
import { hsv2rgb, rgb2css } from 'lib/color'
import ProgressBar from 'components/progress-bar'

export default function Home({
  timeSinceWakingUp,
  progress,
  updatedOn,
  backgroundColor,
}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <style jsx global>
        {`
          html,
          body,
          #__next {
            background-color: ${backgroundColor};
          }
        `}
      </style>
      <div className="container" style={{ backgroundColor: backgroundColor }}>
        <div className="main">
          <p>
            <span className="score">{timeSinceWakingUp}</span>
          </p>
          <ProgressBar
            color="#dddddd"
            completed={progress}
            percentage={false}
            labelComponent={false}
          />
        </div>
        <div className="footer">
          <p>Updated on {updatedOn}</p>
        </div>
      </div>
    </>
  )
}

export async function getServerSideProps({ params, req }) {
  const rawData = await fetchSleepData()

  const bedtimeEnd = new Date(rawData.bedtime_end)
  const workingHours = (Date.now() - bedtimeEnd) / 1000 / 3600

  return {
    props: {
      timeSinceWakingUp: `${Math.floor(workingHours)} hours`,
      progress: Math.min(Math.floor(100 * (workingHours / 16)), 100),
      updatedOn: rawData.summary_date,
      backgroundColor: rgb2css(
        hsv2rgb(220, 0.6, Math.max(0.1, 1 - workingHours / 16))
      ),
    },
  }
}
