import Head from 'next/head'
import { fetchOuraData } from 'lib/oura'
import { hsv2rgb, rgb2css } from 'lib/color'

export default function Home({ data, backgroundColor }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container" style={{ backgroundColor: backgroundColor }}>
        <div className="main">
          <span className="score">{data.score}</span>
          <span> / 100</span>
        </div>
        <div className="footer">
          <p>Updated on {data.summary_date}</p>
        </div>
      </div>
    </>
  )
}

export async function getServerSideProps({ params, req }) {
  // const example = {
  //   summary_date: '2021-07-31',
  //   period_id: 0,
  //   score: 68,
  //   score_activity_balance: 75,
  //   score_hrv_balance: 76,
  //   score_previous_day: 85,
  //   score_previous_night: 70,
  //   score_recovery_index: 67,
  //   score_resting_hr: 88,
  //   score_sleep_balance: 15,
  //   score_temperature: 67,
  //   rest_mode_state: 0,
  // }
  const data = await fetchOuraData()
  const color = hsv2rgb(210, 0.6, data.score / 100 - 0.3)

  return { props: { data, backgroundColor: rgb2css(color) } }
}
